version: 2
jobs:
  test:
    working_directory: ~/gorgon
    docker:
      - image: ruby:2.4.7
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-goenv.sh
      - run: ./scripts/ci/steps/test.sh
  release:
    working_directory: ~/gorgon
    docker:
      - image: ruby:2.4.7
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-goenv.sh
      - run: ./scripts/ci/steps/release.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          filters:
            branches:
              only: master
#      - release:
#          filters:
#            branches:
#              only: master